# Docker Compose file for ELK stack

# Make sure to change the name of the image if you have built your own!

elk:
  image: hermanjunge/elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5000:5000"
  volumes:
    - ./tls/cert:/etc/pki/tls/cert
    - ./tls/secret:/etc/pki/tls/secret
    - ./filters:/etc/logstash/conf.d
    - ./bin:/usr/local/bin
